### ISSUE TITLE
Fastq files are not picked up by processing.py 

### ISSUE THREAD

**Issue by hailiangmei** [TRON-Bioinformatics/EasyFuse#3]
Hi @patricksorn @ibn-salem 

I was trying to test the singularity container (based on your docker image). The tool seems running but it has trouble loading input fastq files. Do you have some suggestion how I could address this issue? Thanks a lot!

```
(base) hmei@res-hpc-lo02:/exports/sascstudent/fven/Leon/easyfuse$ /share/software/singularity/3.9.2/bin/singularity exec --containall --bind /exports/sascstudent/fven/Leon/easyfuse/easyfuse_ref:/ref --bind /exports/sascstudent/fven/Leon/easyfuse/data:/data /exports/sascstudent/fven/Leon/easyfuse/easyfuse_1.3.4.sif ls /data -trl
total 100085
drwxr-xr-x 2 hmei SHARK-SASC-students       96 Jan 22 14:53 results
-rw-r--r-- 1 hmei SHARK-SASC-students 41996924 Jan 22 14:59 SRR1659960_05pc_R1.fastq.gz
-rw-r--r-- 1 hmei SHARK-SASC-students 42979652 Jan 22 15:00 SRR1659960_05pc_R2.fastq.gz


(base) hmei@res-hpc-lo02:/exports/sascstudent/fven/Leon/easyfuse$ /share/software/singularity/3.9.2/bin/singularity exec --containall --bind /exports/sascstudent/fven/Leon/easyfuse/easyfuse_ref:/ref --bind /exports/sascstudent/fven/Leon/easyfuse/data:/data /exports/sascstudent/fven/Leon/easyfuse/easyfuse_1.3.4.sif python /code/easyfuse-1.3.4/processing.py -i /data -o /data/results/

Going to process the following read files...

Going to process the following read files...
Fastq file 0: []
Traceback (most recent call last):
  File "/code/easyfuse-1.3.4/processing.py", line 385, in <module>
    main()
  File "/code/easyfuse-1.3.4/processing.py", line 379, in main
    proc.run(args.tool_support)
  File "/code/easyfuse-1.3.4/processing.py", line 64, in run
    left, right, sample_id = IOMethods.get_fastq_files(self.input_paths, self.logger)
  File "/code/easyfuse-1.3.4/misc/io_methods.py", line 78, in get_fastq_files
    forrev = re.search('_R?([1-2])(_|[.]f)', path_leaf(fq_file)).group(1)
  File "/code/easyfuse-1.3.4/misc/io_methods.py", line 111, in path_leaf
    head, tail = ntpath.split(path)
  File "/usr/lib/python2.7/ntpath.py", line 191, in split
    return d + head, tail
TypeError: cannot concatenate 'str' and 'list' objects
```

Cheers,
Leon

**Comment by patricksorn** [comment]
Hi Leon,

first of all, thanks for pointing out this issue. Somehow the ntpath library resolves your folder /data as a list and therefore cannot parse the FASTQ filename. We already replaced the ntpath library for the next release with something more reliable. Try using the absolute paths of the FASTQ files in the "-i" parameter in the meantime:
"python /code/easyfuse-1.3.4/processing.py -i /data/*.fastq.gz -o /data/results/"

Cheers,
Patrick

**Comment by hailiangmei** [comment]
Hi Patrick,

Thanks for a swift response! I tried your suggestion and then received a new error.

```
Going to process the following read files...
Running EasyFuse-Summary-1643110642_CMD0
CMD: ['python', '/code/easyfuse-1.3.4/summarize_data.py', '--input', '/data/results', '--model_predictions']                                                                                               

Error: Command "['python', '/code/easyfuse-1.3.4/summarize_data.py', '--input', '/data/results', '--model_predictions']" returned non-zero exit status                                                     
Traceback (most recent call last):
  File "/code/easyfuse-1.3.4/summarize_data.py", line 14, in <module>
    from join_data import DataJoining
  File "/code/easyfuse-1.3.4/join_data.py", line 14, in <module>
    import pandas as pd
ImportError: No module named pandas
```
If I checked the singularity container I converted using your docker image, indeed pandas is not included. Is this sth you could fix relatively easy? Thanks!

```
(base) hmei@res-hpc-lo02:~$ /share/software/singularity/3.9.2/bin/singularity shell /exports/sascstudent/fven/Leon/easyfuse/easyfuse_1.3.4.sif                                                             
Singularity> python
Python 2.7.17 (default, Feb 27 2021, 15:10:58)
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pandas
>>>
```
Thanks again,
Leon

**Comment by Zack-Ely** [comment]
Hey Patrick and Leon,

I am currently having the same issue with Singularity on our cluster. Did either of you ever identify a fix?

Best,
Zack

**Comment by Zack-Ely** [comment]
Adding to the above: in the Singularity container, I ran pip install pandas==0.24.0, which got me past the error, but now there is notoutput in the FusionSummary directory. Could you help me troubleshoot this?

I get this from the processing log: 
2022-04-19 22:39:22 DEBUG Created folder /net/GeneFusion/outputs/P151
2022-04-19 22:39:22 INFO Starting easyfuse: CMD - python /code/easyfuse-1.3.4/processing.py -i /net/GeneFusion/input_fastqs -o /net/GeneFusion/outputs/P151
2022-04-19 22:39:22 INFO Pipeline Version: 1.3.4
2022-04-19 22:39:22 INFO Reference Genome: hg38, Reference Transcriptome: ensembl
2022-04-19 22:39:22 DEBUG Submitting slurm job: CMD - python /code/easyfuse-1.3.4/summarize_data.py --input /net/GeneFusion/outputs/P151 --model_predictions; PATH - /net/GeneFusion/outputs/P151; DEPS - []

**Comment by patricksorn** [comment]
Hi @hailiangmei @Zack-Ely ,

pandas installation is included in the Docker, but something must have changed in the Anaconda repository and therefore pandas cannot be fetched. I will find a solution for this. In the meantime maybe it helps to delete the output folder and start a new run, because the sample database may be flawed because of this error.

Best,
Patrick

**Comment by Zack-Ely** [comment]
Thanks for the reply, Patrick. I will delete the output folder, try again, and get back soon.

**Comment by Elizabeth237** [comment]
Hi Patrick and Leon,

I have tried as you said before, but the pipeline still cannot work well.  there is no output in the FusionSummary directory.


/share/app/singularity/3.2.0/bin/singularity exec --containall --bind /tools/easyfuse/easyfuse_ref:/ref --bind /tools/easyfuse/test:/data /tools/easyfuse/easyfuse-1.3.4.simg python /code/easyfuse-1.3.4/processing.py -i /data/*.fq.gz -o /data/result/
Going to process the following read files...
Running EasyFuse-Summary-1650876801_CMD0
CMD: ['python', '/code/easyfuse-1.3.4/summarize_data.py', '--input', '/data/result', '--model_predictions']
Created folder /data/result/FusionSummary
Found 0 (partially) processed samples in /data/result. Data will be collected from 0 samples for which fetchdata has been run.

Could you help me troubleshoot this?
Thanks a lot!

Best,
Ruby

**Comment by patricksorn** [comment]
Hi,

of course we can troubleshoot this issue. Can you maybe look into your /data/result/ folder and look into the Sample_*/fusion/*/ folders and look if there is any output written there. If that is the case in all folders you might have a look into the logfile Sample_*/fetchdata/fetchdata.log and look if there were some errors. If so, please send me a sample logfile.

Best regards,
Patrick

**Comment by Elizabeth237** [comment]
> Hi, Patrick

Thanks for your reply. I have figure out a way to solve it. 

In this script "code/easyfuse-1.3.4/misc/io_methods.py" (about line 65："elif os.path.isfile(path) and path.endswith((".fastq.gz", ".fq.gz", ".fq", ".fastq")"),  "os.path.isfile(path)" cannot find the path in singularity environment. I just comment out "os.path.isfile(path)"  and change it to " elif path.endswith((".fastq.gz", ".fq.gz", ".fq", ".fastq")):" and this issue are solved.

However, this pipeline also cannot work well.

Error: Command "['/code/easyfuse-1.3.4/misc/qc_parser.py', '-i', '/data/results/Sample_test/qc/test_R1_fastqc/fastqc_data.txt', '/data/results/Sample_test/qc/test_R2_fastqc/fastqc_data.txt', '-o', '/data/results/Sample_test/qc/qc_table.txt']" returned non-zero exit status
Traceback (most recent call last):
  File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 90, in <module>
    main()
  File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 86, in main
    qmap = p.parse_quality(file, args.qc_table)
  File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 24, in parse_quality
    with open(infile) as inf:
IOError: [Errno 2] No such file or directory: '/data/results/Sample_test/qc/test_R1_fastqc/fastqc_data.txt

processing log:
2022-04-26 08:13:56 DEBUG Created folder /data/results
2022-04-26 08:13:56 INFO Starting easyfuse: CMD - python /code/easyfuse-1.3.4/processing.py -i /data/test_R1.fastq.gz /data/test_R2.fastq.gz -o /data/results
2022-04-26 08:13:56 INFO Pipeline Version: 1.3.4
2022-04-26 08:13:56 INFO Reference Genome: hg38, Reference Transcriptome: ensembl
2022-04-26 08:13:56 INFO Processing Sample ID: test (paired end)
2022-04-26 08:13:56 INFO Sample 1: /data/test_R1.fastq.gz
2022-04-26 08:13:56 INFO Sample 2: /data/test_R2.fastq.gz
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/qc
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/qc/skewer
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/filtered_reads
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/expression
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/expression/star
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/fusion
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/fusion/mapsplice
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/fusion/fusioncatcher
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/fusion/starfusion
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/fusion/infusion
2022-04-26 08:13:56 DEBUG Created folder /data/results/Sample_test/fusion/soapfuse
2022-04-26 08:13:57 DEBUG Created folder /data/results/Sample_test/fetchdata
2022-04-26 08:13:57 DEBUG Submitting QC run to slurm
2022-04-26 08:13:57 DEBUG Submitting slurm job: CMD - /code/FastQC/fastqc --nogroup --extract -t 6 -o /data/results/Sample_test/qc /data/test_R1.fastq.gz /data/test_R2.fastq.gz && /code/easyfuse-1.3.4/misc/qc_parser.py -i /data/results/Sample_test/qc/test_R1_fastqc/fastqc_data.txt /data/results/Sample_test/qc/test_R2_fastqc/fastqc_data.txt -o /data/results/Sample_test/qc/qc_table.txt && /code/easyfuse-1.3.4/tool_wrapper/skewer_wrapper.py -q /data/results/Sample_test/qc/qc_table.txt -i /data/test_R1.fastq.gz /data/test_R2.fastq.gz -o /data/results/Sample_test/qc/skewer && /code/easyfuse-1.3.4/misc/samples.py --db_path=/data/results/samples.db --sample_id=test --action=append_state --tool=QC; PATH - /data/results/Sample_test/qc; DEPS - [] 

I think I still need some time to figure out this problems.

Best,

**Comment by bbgbb** [comment]
@Elizabeth237 

Hi, Ruby

I met the same error that you mentioned:

Traceback (most recent call last):
File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 90, in
main()
File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 86, in main
qmap = p.parse_quality(file, args.qc_table)
File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 24, in parse_quality
with open(infile) as inf:
IOError: [Errno 2] No such file or directory: '/data/results/Sample_test/qc/test_R1_fastqc/fastqc_data.txt

Could you tell me how did you fix it?
Thanks a lot!

Best,
bbgbb

**Comment by Elizabeth237** [comment]
> @Elizabeth237
> 
> Hi, Ruby
> 
> I met the same error that you mentioned:
> 
> Traceback (most recent call last): File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 90, in main() File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 86, in main qmap = p.parse_quality(file, args.qc_table) File "/code/easyfuse-1.3.4/misc/qc_parser.py", line 24, in parse_quality with open(infile) as inf: IOError: [Errno 2] No such file or directory: '/data/results/Sample_test/qc/test_R1_fastqc/fastqc_data.txt
> 
> Could you tell me how did you fix it? Thanks a lot!
> 
> Best, bbgbb

I am sorry I forget how I ideal with it.  But I think if you can read the code carefully, you will find the method to fix it well.

**Comment by ibn-salem** [comment]
I assume this is resolved with the latest releases and will close this issue. Feel free to re-open if the issue persists with the latest version.

**Comment by stan-maine** [comment]
Hello, I am having this issue as well when trying to run with singularity. I have tried uncompressed and compressed fastq and the fastq files are still not being identified. I have also tried to use only 1 fastq and specify that 1 fastq exactly. I have put the output from the slurm jobs below for both 1 fastq and using *fastq as you mentioned above. Is there a workaround for this? Thank you!

Output from slurm job:
INFO:    Using cached SIF image
WARNING: skipping mount of /gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/*fastq: stat /gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/*fastq: no such file or directory
FATAL:   container creation failed: mount /gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/*fastq->/data error: while mounting /gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/*fastq: mount source /gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/*fastq doesn't exist


Output of easyfuse_processing.log:
2022-12-20 12:58:15 DEBUG Folder /output already exists
2022-12-20 12:58:15 INFO Starting easyfuse: CMD - python /code/easyfuse/processing.py -i /data   -o /output
2022-12-20 12:58:15 INFO Pipeline Version: 1.3.7
2022-12-20 12:58:15 INFO Reference Genome: hg38, Reference Transcriptome: ensembl
2022-12-20 12:58:15 DEBUG Submitting job: CMD - /code/miniconda3/bin/python /code/easyfuse/summarize_data.py --input /output --model_predictions -c /code/easyfuse/config.ini; PATH - /output; DEPS - []

Fastq files do exist but are not being picked up:
ls /gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/*fastq
/gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/ETV001_L001_R1.fastq  /gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/ETV001_L001_R2.fastq

Command line code: 
singularity exec --containall --bind /gpfs/home/src7305/aifantishome/easyfuse/easyfuse_ref:/ref --bind /gpfs/home/src7305/aifantishome/easyfuse/SOFTLINKS/1_FASTQ_TEST/*fastq:/data \
--bind /gpfs/home/src7305/aifantishome/easyfuse/output:/output docker://tronbioinformatics/easyfuse:latest python /code/easyfuse/processing.py -i /data/ -o /output/


output from slurm file when I specify one fastq:
INFO:    Using cached SIF image

Going to process the following read files...
Running EasyFuse-Summary-1671559684_CMD0
CMD: /code/miniconda3/bin/python /code/easyfuse/summarize_data.py --input /output --model_predictions -c /code/easyfuse/config.ini
Error: Command "['/code/miniconda3/bin/python', '/code/easyfuse/summarize_data.py', '--input', '/output', '--model_predictions', '-c', '/code/easyfuse/config.ini']" returned non-zero exit status
b'Traceback (most recent call last):\n  File "/code/easyfuse/summarize_data.py", line 133, in <module>\n    main()\n  File "/code/easyfuse/summarize_data.py", line 130, in main\n    stats.run(args.model_predictions)\n  File "/code/easyfuse/summarize_data.py", line 90, in run\n    print("Found {0} (partially) processed samples in {1}. Data will be collected from {2} samples for which fetchdata has been run.".format(i, self.input_path, count_valid_sample))\nUnboundLocalError: local variable \'i\' referenced before assignment\n'
